### PR TITLE
build: copy actions to dist in new build:deploy script

### PR DESCRIPTION
**Pull request by dckc**
fixes: #54

### CODE REVIEW

**Review by jimscarver — APPROVED** [review]

**Comment by jimscarver** [comment]
merging this with move-spacer

**Comment by dckc** [comment]
Huh? This is already merged to master.

**Comment by jimscarver** [comment]
the build failed on move-space unless i merged this branch so I had to restore it for that purpose.

**Comment by dckc** [comment]
Did you try merging master?

**Comment by jimscarver** [comment]
Yes, that got errors, lost the history but I think I tried it.

**Comment by dckc** [comment]
You're doing something wrong if you can't merge master.

**Pull request merged**
