### PR TITLE
rgov-readme-update

### PR DESCRIPTION
**Pull request by jimscarver**

### CODE REVIEW

**Review by dckc — APPROVED** [review]
I recommend fixing a typo, but it's not critical.

**Comment by dckc** [comment]
@jimscarver why are you editing Ballot.js in this branch?

**Comment by dckc** [comment]
or rather... @Bill-Keuntje why are you editing Ballot.js on this branch?

**Comment by Bill-Keuntje** [comment]
> or rather... @Bill-Keuntje why are you editing Ballot.js on this branch?

Test concerning restrictions on adding to pull requests after-the-fact. I just added a insignificant space to a comment. Sorry for the confusion.

**Pull request merged**
