### PR TITLE
react -  codesandbox template

### PR DESCRIPTION
**Pull request by jimscarver**

### CODE REVIEW

**Review by dckc — CHANGES_REQUESTED** [review]
I don't think this is what you meant. This deletes all the interesting files.

**Comment by jimscarver** [comment]
files are renamed, not deleted.

**Comment by dckc** [comment]
Maybe you meant to rename them, but this PR deletes them.

For example, directory.rho is nowhere to be found in https://github.com/rchain-community/liquid-democracy/tree/react

**Comment by jimscarver** [comment]
yikes! I did not notice. I guess manually re adding the deleted files is the only reasonable way to fix this since to already did commits and pushes...

**Comment by dckc** [comment]
You only pushed on a branch and it hasn't been merged. Just start over.

**Pull request closed without merging**
