### PR TITLE
voting with ocaps

### PR DESCRIPTION
**Pull request by dckc**
Ballot.rho is rewritten to meet requirements for a coop annual meeting and no more: the agenda is set once; there are no methods to add questions.

### CODE REVIEW

**Comment by dckc** [comment]
@jimscarver what do you think about merging this? You can test them (Ballot.rho, Inbox.rho) yourself by deploying them and watching the logs. Or do you want me to walk you through them?

Are there features of the previous versions of Ballot.rho and Inbox.rho that you want to keep?

hm... looks like I have merge conflicts to resolve...

**Comment by dckc** [comment]
> @jimscarver ...
> Are there features of the previous versions of Ballot.rho and Inbox.rho that you want to keep?

This doesn't include delegation; the plan is to layer that on top. I can imagine you might want to see that in action before merging.

**Comment by jimscarver** [comment]
Yes, I want to keep the superfluid democracy support. We can tally votes both ways, direct votes and use of delegate if individuals do not vote.

**Comment by dckc** [comment]
The party tallying the votes need not do anything special to support delegation.

Details to follow.

**Comment by dckc** [comment]
oops; I thought I had rolled this back. hm.

**Pull request merged**
