### PR TITLE
Issue#34 - Liquid Democracy

### PR DESCRIPTION
**Pull request by raviclalwani**
Hackthon 2020

### CODE REVIEW

**Comment by dckc** [comment]
This looks like very nice work!

Here's hoping I find time to test it just a bit so I can merge it.

@jimscarver have you tested it, by chance?

**Comment by jimscarver** [comment]
I witness a test. It works!

**Comment by jimscarver** [comment]
retest results looks good BUT
image
The template fields for sendMail stick for every function!!!
image

**Comment by dckc** [comment]
@raviclalwani now that @jimscarver tested this I'd like to go ahead and merge it. The github button is disabled because this is still a draft PR. Is there any particular reason that it's not ready?

I can merge it using command-line tools.

**Comment by dckc** [comment]
@jimscarver writes:
> The template fields for sendMail stick for every function!!!

escalated to its own issue: #29

**Comment by raviclalwani** [comment]
> @raviclalwani now that @jimscarver tested this I'd like to go ahead and merge it. The github button is disabled because this is still a draft PR. Is there any particular reason that it's not ready?
> 
> I can merge it using command-line tools.

Hi Dan,

I have update the PR and its no longer a draft. There are no code changes.

**Pull request merged**
